receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging: {}
  otlphttp:
    endpoint: "https://TENANT/api/v2/otlp"
    headers:
      Authorization: "Api-Token TOKEN"

processors:
  batch: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp]
